package modelo;
// Generated 26/05/2017 09:19:19 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.faces.bean.ManagedBean;

/**
 * Alumno generated by hbm2java
 */
@ManagedBean
public class Alumno  implements java.io.Serializable {


     private String idMatricula;
     private String nombre;
     private String pass;
     private String estado;
     private Set evaluas = new HashSet(0);

    public Alumno() {
    }

	
    public Alumno(String idMatricula) {
        this.idMatricula = idMatricula;
    }
    public Alumno(String idMatricula, String nombre, String pass, String estado, Set evaluas) {
       this.idMatricula = idMatricula;
       this.nombre = nombre;
       this.pass = pass;
       this.estado = estado;
       this.evaluas = evaluas;
    }
   
    public String getIdMatricula() {
        return this.idMatricula;
    }
    
    public void setIdMatricula(String idMatricula) {
        this.idMatricula = idMatricula;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getEvaluas() {
        return this.evaluas;
    }
    
    public void setEvaluas(Set evaluas) {
        this.evaluas = evaluas;
    }




}


