package modelo;
// Generated 26/05/2017 09:19:19 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.faces.bean.ManagedBean;

/**
 * Docente generated by hbm2java
 */
@ManagedBean
public class Docente  implements java.io.Serializable {


     private Integer idDocente;
     private String nombre;
     private Set evaluas = new HashSet(0);

    public Docente() {
    }

    public Docente(String nombre, Set evaluas) {
       this.nombre = nombre;
       this.evaluas = evaluas;
    }
   
    public Integer getIdDocente() {
        return this.idDocente;
    }
    
    public void setIdDocente(Integer idDocente) {
        this.idDocente = idDocente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getEvaluas() {
        return this.evaluas;
    }
    
    public void setEvaluas(Set evaluas) {
        this.evaluas = evaluas;
    }




}


