package modelo;
// Generated 26/05/2017 09:19:19 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.faces.bean.ManagedBean;

/**
 * Evalua generated by hbm2java
 */
@ManagedBean
public class Evalua  implements java.io.Serializable {


     private Integer idEvaluacion;
     private Alumno alumno;
     private Docente docente;
     private Integer evaluacion;
     private Date fecha;

    public Evalua() {
    }

    public Evalua(Alumno alumno, Docente docente, Integer evaluacion, Date fecha) {
       this.alumno = alumno;
       this.docente = docente;
       this.evaluacion = evaluacion;
       this.fecha = fecha;
    }
   
    public Integer getIdEvaluacion() {
        return this.idEvaluacion;
    }
    
    public void setIdEvaluacion(Integer idEvaluacion) {
        this.idEvaluacion = idEvaluacion;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }
    public Integer getEvaluacion() {
        return this.evaluacion;
    }
    
    public void setEvaluacion(Integer evaluacion) {
        this.evaluacion = evaluacion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


